drop table t;
create table t(ID INTEGER not null constraint \"t_pk\" primary key, TITLE VARCHAR(50), CREATED TIMESTAMP(6)) DATA CAPTURE CHANGES;
COMMIT;

insert into t(ID, CREATED) values (1, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (2, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (3, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (4, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (5, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (6, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (7, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (8, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (9, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (10, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (11, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (12, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (13, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (14, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (15, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (16, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (17, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (18, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (19, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (20, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (21, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (22, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (23, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (24, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (25, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (26, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (27, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (28, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (29, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (30, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (31, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (32, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (33, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (34, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (35, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (36, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (37, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (38, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (39, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (40, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (41, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (42, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (43, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (44, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (45, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (46, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (47, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (48, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (49, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (50, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (51, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (52, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (53, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (54, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (55, CURRENT_TIMESTAMP);
insert into t(ID, CREATED) values (56, CURRENT_TIMESTAMP);
update t set TITLE='123' where ID=1;
update t set TITLE='123' where ID=2;
update t set TITLE='123' where ID=3;
update t set TITLE='123' where ID=4;
update t set TITLE='123' where ID=5;
update t set TITLE='123' where ID=6;
update t set TITLE='123' where ID=7;
update t set TITLE='123' where ID=8;
update t set TITLE='123' where ID=9;
update t set TITLE='123' where ID=10;
update t set TITLE='123' where ID=11;
update t set TITLE='123' where ID=12;
update t set TITLE='123' where ID=13;
update t set TITLE='123' where ID=14;
update t set TITLE='123' where ID=15;
update t set TITLE='123' where ID=16;
update t set TITLE='123' where ID=17;
update t set TITLE='123' where ID=18;
update t set TITLE='123' where ID=19;
update t set TITLE='123' where ID=20;
update t set TITLE='123' where ID=21;
update t set TITLE='123' where ID=22;
update t set TITLE='123' where ID=23;
update t set TITLE='123' where ID=24;
update t set TITLE='123' where ID=25;
update t set TITLE='123' where ID=26;
update t set TITLE='123' where ID=27;
update t set TITLE='123' where ID=28;
update t set TITLE='123' where ID=29;
update t set TITLE='123' where ID=30;
update t set TITLE='123' where ID=31;
update t set TITLE='123' where ID=32;
update t set TITLE='123' where ID=33;
update t set TITLE='123' where ID=34;
update t set TITLE='123' where ID=35;
update t set TITLE='123' where ID=36;
update t set TITLE='123' where ID=37;
update t set TITLE='123' where ID=38;
update t set TITLE='123' where ID=39;
update t set TITLE='123' where ID=40;
update t set TITLE='123' where ID=41;
update t set TITLE='123' where ID=42;
update t set TITLE='123' where ID=43;
update t set TITLE='123' where ID=44;
update t set TITLE='123' where ID=45;
update t set TITLE='123' where ID=46;
update t set TITLE='123' where ID=47;
update t set TITLE='123' where ID=48;
update t set TITLE='123' where ID=49;
update t set TITLE='123' where ID=50;
update t set TITLE='123' where ID=51;
update t set TITLE='123' where ID=52;
update t set TITLE='123' where ID=53;
update t set TITLE='123' where ID=54;
update t set TITLE='123' where ID=55;
update t set TITLE='123' where ID=56;
COMMIT;
